### ISSUE TITLE
Create the complaint database

### ISSUE THREAD

**Issue by sshivam95** [DevCom-IITB/instiapp-api#202]
Create the complaint database in the portal using the model forms with the following schema:

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(30),
  last_name VARCHAR(30),
  email_address VARCHAR(1000),
  password VARCHAR(30),
  join_date DATE,
  mobile_no VARCHAR(30),
  user_uri VARCHAR(30),
  liked_complaints INT[]
) ;

CREATE INDEX IF NOT EXISTS n_i ON users(first_name);

CREATE TABLE IF NOT EXISTS complaints (
  id SERIAL PRIMARY KEY,
  rating VARCHAR(30),
  description VARCHAR(10000),
  report_date DATE,
  status VARCHAR(30),
  user_id INT NOT NULL,
  lat FLOAT(8),
  lon FLOAT(8),
  alt FLOAT(8),
  location_description VARCHAR(10000),
  ward_name VARCHAR(30),
  city VARCHAR(30),
  state VARCHAR(30),
  zipcode VARCHAR(30),
  ward_id BIGINT,
  admin_country VARCHAR(30),
  admin_zone VARCHAR(30),
  admin_district VARCHAR(30),
  users_liked INT[],
  comments INT[],
  FOREIGN KEY (user_id) REFERENCES users(id)
) ;

CREATE TABLE IF NOT EXISTS media (
  id SERIAL PRIMARY KEY,
  description VARCHAR(500),
  name VARCHAR(50),
  complaint_id INT CHECK (complaint_id > 0) NOT NULL,
  hash VARCHAR(1000000),
  size BIGINT,
  FOREIGN KEY (complaint_id) REFERENCES complaints(id)
) ;

CREATE TABLE IF NOT EXISTS tag_uris (
  id SERIAL PRIMARY KEY,
  tag_uri VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS complaint_tag_uris (
  complaint_id INT NOT NULL,
  tag_id INT NOT NULL,
  FOREIGN KEY (complaint_id) REFERENCES complaints(id),
  FOREIGN KEY (tag_id) REFERENCES tag_uris(id),
  UNIQUE (complaint_id,tag_id)
);

CREATE TABLE IF NOT EXISTS comment (
  id SERIAL PRIMARY KEY,
  time DATE,
  text VARCHAR(500),
  complaint_id INT NOT NULL,
  user_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS complaints_liked_users (
   user_id INT NOT NULL,
   complaint_id INT NOT NULL,
   FOREIGN KEY (user_id) REFERENCES users(id),
   FOREIGN KEY (complaint_id) REFERENCES complaints(id)
);

**Comment by pulsejet** [comment]
Creating the necessary models for each table (except intermediary relating tables, which Django should take care of with ManyToManyField) should be easy. Please read the contribution guidelines in README.md if you'll be opening a PR for this.

**Comment by pulsejet** [comment]
Done with #211
