### ISSUE TITLE
End of Sentence character exceeds allowed length for Event Title

### ISSUE THREAD

**Issue by ydidwania** [DevCom-IITB/instiapp-api#286]
The end of sentence character `\0` in the `Event Title` results in an error even if it is 50 characters long.
It might be useful to increase the allowed length to 51 or 60 for safety.
Changing the `max_length` property might lead to issues during migration.
Be careful :)

**Comment by pulsejet** [comment]
Let's change it to 60 to be safe. Migrations *will* hopefully not cause any issues, but I will have a backup in place just in case.

**Comment by pulsejet** [comment]
Maybe get someone from DevCom to fix this @e-aakash
