### ISSUE TITLE
Add email feature along with a model for storing emails of authorities

### ISSUE THREAD

**Issue by samjakes** [DevCom-IITB/instiapp-api#298]
Here's the code for the authorities model:

```
class Authorities(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    name = models.CharField(max_length=30, blank=True, null=True)
    email = models.EmailField(max_length=50, blank=True, null=True, unique=True)

    class Meta:
        verbose_name = 'Authority Email'
        verbose_name_plural = 'Authority Emails'

    def __str__(self):
        return self.email
```

A field will be added in the complaints model called 'authority email' as shown below:
```
authority_email = models.ForeignKey(Authorities, on_delete=models.CASCADE, null=True, blank=True, to_field='email')
```

In the relevant ModelAdmin for Complaints, I've displayed this field and made it editable. I've added admin actions within the ModelAdmin, as is suggested by django. This made it more convenient to test the functions as well. The issue is that pylint keeps telling me that those methods could be functions, and yet the decision to keep them as methods is deliberate and if it doesn't break logic then it should be harmless.

I've fixed the warning about "too many local variables" by removing an unneeded variable. The mass mail feature has been confirmed to work, and the sender's ID will be set to 'webmaster@localhost', which is the value of the 'DEFAULT_FROM_VARIABLE' as indicated in [the django documentation](https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-DEFAULT_FROM_EMAIL). 

**Note:** You might want to set up the mail backend settings as they are on the production server and test whether the feature works for you and if there's any improvement to be made. As the documentation lists 'webmaster@localhost' to be the email for generic automated correspondence, that's the one I've listed as the sender for email IDs by default. 

In venter/admin.py:
line 101
```
sender_id = settings_base.DEFAULT_FROM_EMAIL
``` 
These features have been tested in venter/tests.py and have passed coverage tests which i've run using the command "coverage run manage.py test --settings backend.settings_test; coverage html"

**Comment by pulsejet** [comment]
Could you please describe how exactly the implementation for this is planned by editing the first comment? This'll help prevent delays later.

**Comment by pulsejet** [comment]
> The issue is that pylint keeps telling me that those methods could be functions, and yet the decision to keep them as methods is deliberate and if it doesn't break logic then it should be harmless.

It _is_ harmless to be fair, but it can have performance benefits, however small they might be, and in a setup as performance constrained as ours, we want to do the best we can. Check [this answer](https://stackoverflow.com/a/22589883)

> As the documentation lists 'webmaster@localhost' to be the email for generic automated correspondence, that's the one I've listed as the sender for email IDs by default.

This is fine. I'll set an email for this statically in the production settings. However using `settings_base` is _not_ fine, cause then the production settings will never be used. Check my comment on #299
