### ISSUE TITLE
Event dates shown as 11st instead of 11th

### ISSUE THREAD

**Issue by ydidwania** [DevCom-IITB/instiapp-api#323]
I believe this the same for ~12th~ `12nd` and ~13th~ `13rd`

**Comment by pulsejet** [comment]
This belongs to [pulsejet/iitb-app-angular](https://github.com/pulsejet/iitb-app-angular) I think, cause the server just returns ISO 8601 timestamps.

**Comment by pulsejet** [comment]
Fixed with https://github.com/pulsejet/iitb-app-angular/commit/9d61d2a2b9867f81492254d263ed9bafa376d241
