### ISSUE TITLE
Add flag official_post to BodyRole

### ISSUE THREAD

**Issue by pulsejet** [DevCom-IITB/instiapp-api#382]
* Boolean field `official_post` in `BodyRole` model. 
* Defaults to `True`.
* Add to `RoleSerializer` and add a test.

**Comment by HrushikeshBodas** [comment]
Ill take this up

**Comment by pulsejet** [comment]
Go ahead @HrushikeshBodas

**Comment by pulsejet** [comment]
Fixed with #383
