### ISSUE TITLE
Implement event tagging

### ISSUE THREAD

**Issue by pulsejet** [DevCom-IITB/instiapp-api#39]
Events can be tagged and users can mark tags as interested. The prioritizer will give more weight to tags with interests.

**Comment by ydidwania** [comment]
https://django-tagging.readthedocs.io/en/develop/

**Comment by ydidwania** [comment]
http://radiac.net/projects/django-tagulous/documentation/
I found  out  this is better, since it also has auto-complete, the installation is tricky though

**Comment by Krishna-Baldwa** [comment]
Done
