### ISSUE TITLE
Cap date range in events API

### ISSUE THREAD

**Issue by pulsejet** [DevCom-IITB/instiapp-api#441]
Currently we can list events by the date range for the calendar. This range needs to have a cap, e.g. don't allow listing more than 3 months' events at once.

**Comment by abhishek2x** [comment]
I am not sure how the frontend UI looks like. But, here's a simple hack. In Angular, client-side code, we can disable the option of choosing a future date from the calendar. This might work fine.

**Comment by pulsejet** [comment]
That's not the point. The point is that if a malicious user queries for a very long date range, then we run through the entire database (DoS).

**Comment by abhishek2x** [comment]
Okay, I understand. We can create a check in the `EventViewSet.list` method for the duration between start and end date.

**Comment by pulsejet** [comment]
Yes

**Comment by Krishna-Baldwa** [comment]
Done
